const translations = {
    tr: {
        home: "Ana Sayfa",
        scans: "Taramalar",
        files: "Süreçler",
        net: "Ağ",
        logs: "Loglar",
        settings: "Ayarlar",
        status_secure: "SİSTEM GÜVENLİ",
        node: "DÜĞÜM",
        threat_detection: "TEHDİT ALGILAMA",
        firewall_shield: "GÜVENLİK DUVARI",
        quarantine: "KARANTİNA",
        global_network: "KÜRESEL AĞ DURUMU",
        initiate_scan: "TARAMAYI BAŞLAT",
        configure: "YAPILANDIR",
        access_storage: "DEPOYA ERİŞ",
        system_activity: "SİSTEM AKTİVİTE MONİTÖRÜ",
        active_protections: "AKTİF KORUMALAR",
        vault_empty: "KASA BOŞ",
        traffic: "TRAFİK",
        encryption: "ŞİFRELEME",
        quick_analysis: "HIZLI ANALİZ",
        full_scan: "TAM SİSTEM TARAMASI",
        heuristic_scan: "HEURISTIC TARAMA",
        active_nodes: "AKTİF AĞ DÜĞÜMLERİ",
        traffic_control: "TRAFİK KONTROLÜ",
        process_monitor: "SİSTEM SÜREÇ MONİTÖRÜ",
        terminal_control: "TERMİNAL KONTROLÜ",
        terminate_now: "ŞİMDİ SONLANDIR",
        scan_processes: "Süreçleri Tara",
        latest_event: "Sistem başlatıldı. Komut bekleniyor...",
        developed_by: "GELİŞTİREN: CYPHERN0X",
        shutdown_after: "Tarama bitince bilgisayarı kapat"
    },
    en: {
        home: "Home",
        scans: "Scans",
        files: "Processes",
        net: "Net",
        logs: "Logs",
        settings: "Settings",
        status_secure: "SYSTEM SECURE",
        node: "NODE",
        threat_detection: "THREAT DETECTION",
        firewall_shield: "FIREWALL SHIELD",
        quarantine: "QUARANTINE",
        global_network: "GLOBAL NETWORK STATUS",
        initiate_scan: "INITIATE SCAN",
        configure: "CONFIGURE",
        access_storage: "ACCESS STORAGE",
        system_activity: "SYSTEM ACTIVITY MONITOR",
        active_protections: "ACTIVE PROTECTIONS",
        vault_empty: "VAULT IS EMPTY",
        traffic: "TRAFFIC",
        encryption: "ENCRYPTION",
        quick_analysis: "QUICK ANALYSIS",
        full_scan: "FULL SYSTEM SCAN",
        heuristic_scan: "HEURISTIC SCAN",
        active_nodes: "ACTIVE NETWORK NODES",
        traffic_control: "TRAFFIC CONTROL",
        process_monitor: "SYSTEM PROCESS MONITOR",
        terminal_control: "TERMINAL CONTROL",
        terminate_now: "TERMINATE NOW",
        scan_processes: "Scan Processes",
        latest_event: "System initialized. Waiting for commands...",
        developed_by: "DEVELOPED BY CYPHERN0X",
        shutdown_after: "Shutdown computer after scan"
    },
    de: {
        home: "Startseite",
        scans: "Scans",
        files: "Prozesse",
        net: "Netzwerk",
        logs: "Protokolle",
        settings: "Einstellungen",
        status_secure: "SYSTEM SICHER",
        node: "KNOTEN",
        threat_detection: "BEDROHUNGSERKENNUNG",
        firewall_shield: "FIREWALL-SCHUTZ",
        quarantine: "QUARANTÄNE",
        global_network: "NETZWERKSTATUS",
        initiate_scan: "SCAN STARTEN",
        configure: "KONFIGURIEREN",
        access_storage: "SPEICHER ÖFFNEN",
        system_activity: "SYSTEMÜBERWACHUNG",
        active_protections: "AKTIVER SCHUTZ",
        vault_empty: "TRESOR LEER",
        traffic: "VERKEHR",
        encryption: "VERSCHLÜSSELUNG",
        quick_analysis: "SCHNELLANALYSE",
        full_scan: "VOLLSTÄNDIGER SCAN",
        heuristic_scan: "HEURISTISCHER SCAN",
        active_nodes: "AKTIVE KNOTEN",
        traffic_control: "VERKEHRSKONTROLLE",
        process_monitor: "PROZESSMONITOR",
        terminal_control: "TERMINAL-KONTROLLE",
        terminate_now: "JETZT BEENDEN",
        scan_processes: "Prozesse scannen",
        latest_event: "System initialisiert. Warten...",
        developed_by: "ENTWICKELT VON CYPHERN0X",
        shutdown_after: "Computer nach Scan ausschalten"
    },
    ru: {
        home: "Главная",
        scans: "Сканирование",
        files: "Процессы",
        net: "Сеть",
        logs: "Логи",
        settings: "Настройки",
        status_secure: "СИСТЕМА ЗАЩИЩЕНА",
        node: "УЗЕЛ",
        threat_detection: "ОБНАРУЖЕНИЕ УГРОЗ",
        firewall_shield: "ФАЕРВОЛ",
        quarantine: "КАРАНТИН",
        global_network: "СТАТУС СЕТИ",
        initiate_scan: "НАЧАТЬ СКАН",
        configure: "НАСТРОИТЬ",
        access_storage: "ОТКРЫТЬ ХРАНИЛИЩЕ",
        system_activity: "МОНИТОР АКТИВНОСТИ",
        active_protections: "АКТИВНАЯ ЗАЩИТА",
        vault_empty: "ХРАНИЛИЩЕ ПУСТО",
        traffic: "ТРАФИК",
        encryption: "ШИФРОВАНИЕ",
        quick_analysis: "БЫСТРЫЙ АНАЛИЗ",
        full_scan: "ПОЛНЫЙ СКАН",
        heuristic_scan: "ЭВРИСТИЧЕСКИЙ СКАН",
        active_nodes: "АКТИВНЫЕ УЗЛЫ",
        traffic_control: "КОНТРОЛЬ ТРАФИКА",
        process_monitor: "МОНИТОР ПРОЦЕССОВ",
        terminal_control: "УПРАВЛЕНИЕ",
        terminate_now: "ЗАВЕРШИТЬ",
        scan_processes: "Скан процессов",
        latest_event: "Система запущена. Ожидание...",
        developed_by: "РАЗРАБОТАНО CYPHERN0X",
        shutdown_after: "Выключить ПК после сканирования"
    },
    fr: {
        home: "Accueil",
        scans: "Analyses",
        files: "Processus",
        net: "Réseau",
        logs: "Journaux",
        settings: "Paramètres",
        status_secure: "SYSTÈME SÉCURISÉ",
        node: "NŒUD",
        threat_detection: "DÉTECTION DE MENACES",
        firewall_shield: "BOUCLIER FIREWALL",
        quarantine: "QUARANTAINE",
        global_network: "ÉTAT DU RÉSEAU",
        initiate_scan: "LANCER L'ANALYSE",
        configure: "CONFIGURER",
        access_storage: "ACCÉDER AU STOCKAGE",
        system_activity: "MONITEUR D'ACTIVITÉ",
        active_protections: "PROTECTIONS ACTIVES",
        vault_empty: "COFFRE VIDE",
        traffic: "TRAFIC",
        encryption: "CHIFFREMENT",
        quick_analysis: "ANALYSE RAPIDE",
        full_scan: "ANALYSE COMPLÈTE",
        heuristic_scan: "ANALYSE HEURISTIQUE",
        active_nodes: "NŒUDS ACTIFS",
        traffic_control: "CONTRÔLE DU TRAFIC",
        process_monitor: "MONITEUR DE PROCESSUS",
        terminal_control: "CONTRÔLE TERMINAL",
        terminate_now: "TERMINER MAINTENANT",
        scan_processes: "SCANNER PROCESSUS",
        latest_event: "Système initialisé. En attente...",
        developed_by: "DÉVELOPPÉ PAR CYPHERN0X"
    },
    es: {
        home: "Inicio",
        scans: "Análisis",
        files: "Procesos",
        net: "Red",
        logs: "Registros",
        settings: "Ajustes",
        status_secure: "SISTEMA SEGURO",
        node: "NODO",
        threat_detection: "DETECCIÓN DE AMENAZAS",
        firewall_shield: "ESCUDO DE FIREWALL",
        quarantine: "CUARENTENA",
        global_network: "ESTADO DE LA RED",
        initiate_scan: "INICIAR ANÁLISIS",
        configure: "CONFIGURAR",
        access_storage: "ACCEDER AL ALMACÉN",
        system_activity: "MONITOR DE ACTIVIDAD",
        active_protections: "PROTECCIONES ACTIVAS",
        vault_empty: "BÓVEDA VACÍA",
        traffic: "TRÁFICO",
        encryption: "CIFRADO",
        quick_analysis: "ANÁLISIS RÁPIDO",
        full_scan: "ANÁLISIS COMPLETO",
        heuristic_scan: "ANÁLISIS HEURÍSTICO",
        active_nodes: "NODOS ACTIVOS",
        traffic_control: "CONTROL DE TRÁFICO",
        process_monitor: "MONITOR DE PROCESOS",
        terminal_control: "CONTROL DE TERMINAL",
        terminate_now: "TERMINAR AHORA",
        scan_processes: "ESCANEAR PROCESOS",
        latest_event: "Sistema inicializado. Esperando...",
        developed_by: "DESARROLLADO POR CYPHERN0X"
    },
    ja: {
        home: "ホーム",
        scans: "スキャン",
        files: "プロセス",
        net: "ネット",
        logs: "ログ",
        settings: "設定",
        status_secure: "システム保護中",
        node: "ノード",
        threat_detection: "脅威検出",
        firewall_shield: "ファイアウォール",
        quarantine: "隔離室",
        global_network: "ネットワーク状態",
        initiate_scan: "スキャン開始",
        configure: "設定",
        access_storage: "ストレージを表示",
        system_activity: "システムモニター",
        active_protections: "有効な保護",
        vault_empty: "保管庫は空です",
        traffic: "トラフィック",
        encryption: "暗号化",
        quick_analysis: "クイックスキャン",
        full_scan: "フルスキャン",
        heuristic_scan: "ヒューリスティックスキャン",
        active_nodes: "アクティブなノード",
        traffic_control: "トラフィック制御",
        process_monitor: "プロセスモニター",
        terminal_control: "ターミナル制御",
        terminate_now: "今すぐ終了",
        scan_processes: "プロセスをスキャン",
        latest_event: "システムが初期化されました。待機中...",
        developed_by: "開発者: CYPHERN0X"
    },
    zh: {
        home: "首页",
        scans: "扫描",
        files: "进程",
        net: "网络",
        logs: "日志",
        settings: "设置",
        status_secure: "系统安全",
        node: "节点",
        threat_detection: "威胁检测",
        firewall_shield: "防火墙保护",
        quarantine: "隔离区",
        global_network: "网络状态",
        initiate_scan: "开始扫描",
        configure: "配置",
        access_storage: "访问存储",
        system_activity: "系统活动监控",
        active_protections: "活动保护",
        vault_empty: "仓库为空",
        traffic: "流量",
        encryption: "加密",
        quick_analysis: "快速分析",
        full_scan: "全盘扫描",
        heuristic_scan: "启发式扫描",
        active_nodes: "活动节点",
        traffic_control: "流量控制",
        process_monitor: "进程监控",
        terminal_control: "终端控制",
        terminate_now: "立即终止",
        scan_processes: "扫描进程",
        latest_event: "系统已初始化。等待指令...",
        developed_by: "开发者: CYPHERN0X"
    },
    it: {
        home: "Home",
        scans: "Scansioni",
        files: "Processi",
        net: "Rete",
        logs: "Log",
        settings: "Impostazioni",
        status_secure: "SISTEMA PROTETTO",
        node: "NODO",
        threat_detection: "RILEVAMENTO MINACCE",
        firewall_shield: "SCUDO FIREWALL",
        quarantine: "QUARANTENA",
        global_network: "STATO RETE",
        initiate_scan: "AVVIA SCANSIONE",
        configure: "CONFIGURA",
        access_storage: "ACCEDI AL DEPOSITO",
        system_activity: "MONITORAGGIO SISTEMA",
        active_protections: "PROTEZIONI ATTIVE",
        vault_empty: "CAVÒ VUOTO",
        traffic: "TRAFFICO",
        encryption: "CRITTOGRAFIA",
        quick_analysis: "ANALISI RAPIDA",
        full_scan: "SCANSIONE COMPLETA",
        heuristic_scan: "SCANSIONE EURISTICA",
        active_nodes: "NODI ATTIVI",
        traffic_control: "CONTROLLO TRAFFICO",
        process_monitor: "MONITOR PROCESSI",
        terminal_control: "CONTROLLO TERMINALE",
        terminate_now: "TERMINA ORA",
        scan_processes: "SCANSIONE PROCESSI",
        latest_event: "Sistema inizializzato. In attesa...",
        developed_by: "SVILUPPATO DA CYPHERN0X"
    },
    pt: {
        home: "Início",
        scans: "Verificações",
        files: "Processos",
        net: "Rede",
        logs: "Logs",
        settings: "Ajustes",
        status_secure: "SISTEMA SEGURO",
        node: "NÓ",
        threat_detection: "DETECÇÃO DE AMEAÇAS",
        firewall_shield: "ESCUDO DE FIREWALL",
        quarantine: "QUARENTENA",
        global_network: "ESTADO DA REDE",
        initiate_scan: "INICIAR VERIFICAÇÃO",
        configure: "CONFIGURAR",
        access_storage: "ACESSAR ARMAZÉM",
        system_activity: "MONITOR DE ATIVIDADE",
        active_protections: "PROTEÇÕES ATIVAS",
        vault_empty: "COFRE VAZIO",
        traffic: "TRÁFEGO",
        encryption: "CRIPTOGRAFIA",
        quick_analysis: "ANÁLISE RÁPIDA",
        full_scan: "VERIFICAÇÃO COMPLETA",
        heuristic_scan: "VERIFICAÇÃO HEURÍSTICA",
        active_nodes: "NÓS ATIVOS",
        traffic_control: "CONTROLE DE TRÁFEGO",
        process_monitor: "MONITOR DE PROCESSOS",
        terminal_control: "CONTROLE DE TERMINAL",
        terminate_now: "ENCERRAR AGORA",
        scan_processes: "VERIFICAR PROCESSOS",
        latest_event: "Sistema inicializado. Aguardando...",
        developed_by: "DESENVOLVIDO POR CYPHERN0X"
    },
    ar: {
        home: "الرئيسية",
        scans: "الفحص",
        files: "العمليات",
        net: "الشبكة",
        logs: "السجلات",
        settings: "الإعدادات",
        status_secure: "النظام مؤمن",
        node: "عقدة",
        threat_detection: "كشف التهديدات",
        firewall_shield: "درع الحماية",
        quarantine: "الحجر الصحي",
        global_network: "حالة الشبكة",
        initiate_scan: "بدء الفحص",
        configure: "تكوين",
        access_storage: "الوصول للمخزن",
        system_activity: "مراقب النشاط",
        active_protections: "الحماية النشطة",
        vault_empty: "المخزن فارغ",
        traffic: "حركة المرور",
        encryption: "التشفير",
        quick_analysis: "فحص سريع",
        full_scan: "فحص كامل",
        heuristic_scan: "فحص استدلالي",
        active_nodes: "العقد النشطة",
        traffic_control: "التحكم في المرور",
        process_monitor: "مراقب العمليات",
        terminal_control: "التحكم في الطرفية",
        terminate_now: "إنهاء الآن",
        scan_processes: "فحص العمليات",
        latest_event: "تم تهيئة النظام. في الانتظار...",
        developed_by: "تطوير بواسطة CYPHERN0X"
    },
    ko: {
        home: "홈",
        scans: "검사",
        files: "프로세스",
        net: "네트워크",
        logs: "로그",
        settings: "설정",
        status_secure: "시스템 보안됨",
        node: "노드",
        threat_detection: "위협 탐지",
        firewall_shield: "방화벽 쉴드",
        quarantine: "격리소",
        global_network: "글로벌 네트워크 상태",
        initiate_scan: "검사 시작",
        configure: "구성",
        access_storage: "저장소 액세스",
        system_activity: "시스템 활동 모니터",
        active_protections: "활성 보호",
        vault_empty: "보관함이 비어 있음",
        traffic: "트래픽",
        encryption: "암호화",
        quick_analysis: "빠른 분석",
        full_scan: "전체 시스템 검사",
        heuristic_scan: "휴리스틱 검사",
        active_nodes: "활성 노드",
        traffic_control: "트래픽 제어",
        process_monitor: "시스템 프로세스 모니터",
        terminal_control: "터미nal 제어",
        terminate_now: "즉시 종료",
        scan_processes: "프로세스 검사",
        latest_event: "시스템이 초기화되었습니다. 대기 중...",
        developed_by: "개발자: CYPHERN0X"
    }
};

module.exports = translations;
